#!/bin/bash

system=$(uname -s)

# Check hssh config exist in /etc folder
if [[ ! -d "/etc/hssh" ]]; then
  sudo mkdir /etc/hssh
fi

# Check hssh config exist in $HOME
if [[ ! -d "$HOME/.config/hssh" ]]; then
  mkdir "$HOME/.config/hssh"
fi

# Check if file config exist in /etc/hssh folder
if [[ ! -f "/etc/hssh/config.yml" ]]; then
  sudo cp ./config.example.yml /etc/hssh/config.yml
fi

# Check if file config exist in $HOME/.config/hssh folder
if [[ ! -f "$HOME/.config/hssh/config" ]]; then
  sudo cp ./config.template.yml "$HOME/.config/hssh/config.yml"
fi

go build hssh

sudo cp ./hssh /core/bin/
