name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test hssh/test
        run: go test hssh/providers/test/github
        run: go test hssh/providers/test/gitlab
      - uses: wangyoucao577/go-release-action@v1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz"
